# -*- mode: dockerfile -*-
### stage0
FROM <REPO_NAME>:<TAG_NAME>-build as build

COPY app /tmp/build
RUN TEMP_FILE=$(mktemp) \
 && chmod 666 "${TEMP_FILE}" \
 && BUILDPACK_LOG_FILE=$TEMP_FILE /bin/herokuish buildpack build \
 && /bin/herokuish slug generate

### stage1
FROM <REPO_NAME>:<TAG_NAME>

COPY --from=build /tmp/slug.tgz /tmp
RUN mkdir -p /app \
 && tar x -C /app -f /tmp/slug.tgz \
 && rm /tmp/slug.tgz
COPY test.sh /
CMD ["bash", "/test.sh"]
