version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
        environment:
          - REPO_NAME=miyucy/herokuishm
          - DOCKER_BUILDKIT=1
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: |
          date -u '+%Y%m%d%H%M%S' > TAG_NAME
          echo "TAG_NAME=$(cat TAG_NAME)"
      - run: |
          TAG_NAME=$(cat TAG_NAME)
          cat Dockerfile.build | \
          docker build --progress plain -t "${REPO_NAME}:${TAG_NAME}-build" -f - .
      - run: |
          TAG_NAME=$(cat TAG_NAME)
          cat Dockerfile | \
          docker build --progress plain -t "${REPO_NAME}:${TAG_NAME}" -f - .
      - run: |
          TAG_NAME=$(cat TAG_NAME)
          cat Dockerfile.test | sed -e "s|<REPO_NAME>|${REPO_NAME}|g" | sed -e "s|<TAG_NAME>|${TAG_NAME}|g" | docker build --progress plain -t "${REPO_NAME}:test" -f - .
      - run: |
          docker run -e PORT=5959 -e USER=herokuishuser "${REPO_NAME}:test"
      - deploy:
          command: |
            docker images "${REPO_NAME}"
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              TAG_NAME=$(cat TAG_NAME)
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker push "${REPO_NAME}:${TAG_NAME}"
              docker push "${REPO_NAME}:${TAG_NAME}-build"
            fi
